version: "2"
services:
  api:
    build: .
    command: npm start
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3334:3334"
    links:
      - mongo
  mongo:
    image: mongo:3.1.9
    volumes_from:
      - data
    ports:
      - "27017:27017"
  data:
    image: busybox:latest
    volumes:
      - /data
  dataconsole:
    build: ./data
    volumes:
      - ./data:/data
      - /data/node_modules
    links:
      - mongo
