apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
  selector:
    name: mongo

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
        - image: mongo:3.0.4
          name: mongo
          ports:
            - containerPort: 27017
              name: mysql
          volumeMounts:
              # This name must match the volumes.name below.
            - name: db-data
              mountPath: "/var/lib/mysql"
      volumes:
        - name: db-data
          gcePersistentDisk:
            # This disk must already exist.
            pdName: db-data
            fsType: ext4